### PR TITLE
fix: `KeyBuilder.buildKeyWithSharedDomain` for EC keys

### LINKED ISSUE #11: Implement `KeyBuilder.buildKeyWithSharedDomain`
Function `KeyBuilder.buildKeyWithSharedDomain` is not implemented correctly.
- Returned key does share the domain by reference.
- It does not create sizes other than 256.

### PR DESCRIPTION
**Pull request by dishmaker**
Fixes #11

### CODE REVIEW

File: simulator/src/main/java/com/licel/jcardsim/crypto/ECKeySharedImpl.java [hunk 1]
```diff
@@ -0,0 +1,153 @@
+/*
+ * Copyright 2011 Licel LLC.
```
Comment (martinpaljak) [inline simulator/src/main/java/com/licel/jcardsim/crypto/ECKeySharedImpl.java]: Might want to set that to your name?

File: simulator/src/main/java/com/licel/jcardsim/crypto/ECPrivateKeySharedImpl.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+     * 
+     * @param keyType      key type
+     * @param keySize      key size it bits
+     * @param sharedDomain key domain parameters, built with
+     *                     KeyBuilder.buildKey(KeyBuilder.ALG_TYPE_EC_FP_PARAMETERS..)
+     *
+     * @see javacard.security.KeyBuilder
+     */
+    public ECPrivateKeySharedImpl(byte keyType, short keySize, byte memoryType, ECKeyImpl sharedDomain) {
+        super(keyType, keySize, memoryType, sharedDomain);
```
Comment (martinpaljak) [inline simulator/src/main/java/com/licel/jcardsim/crypto/ECPrivateKeySharedImpl.java:45]: There was something that made me question the current implementation hierarchy and associated assumptions of BC dependency, but can't find the relevant notes right now.

Comment (dishmaker) [reply simulator/src/main/java/com/licel/jcardsim/crypto/ECPrivateKeySharedImpl.java:45]: For me it was `ECKeyImpl` at first, that made me question why there are `a, b, g, r, fp`, that should not exist for shared version of the key.
But it's simple: `ECKey` is an interface, so `ECKeySharedImpl` does not have to store any domain parameters inside.
